In [69]:
import numpy as np


In [77]:
a = np.zeros((5, 5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [78]:
a[0, 1] = 1
a[1, 3] = 1
a[2, 4] = 1
#a[0, 4] = 1
adj = a
adj


array([[0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [79]:
    adj = adj + np.multiply(adj.T, (adj.T > adj)) - np.multiply(adj, (adj.T > adj))


In [80]:
adj

array([[0., 1., 0., 0., 0.],
       [1., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [81]:
adj0 = adj + np.eye(adj.shape[0])
print(np.dot(adj0, adj0))

[[2. 2. 0. 1. 0.]
 [2. 3. 0. 2. 0.]
 [0. 0. 2. 0. 2.]
 [1. 2. 0. 2. 0.]
 [0. 0. 2. 0. 2.]]


In [67]:
print(np)

array([[0., 1., 0., 0., 1.],
       [1., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       [1., 0., 1., 0., 0.]])